version: '3.9'

services:
  modbusclient:
    container_name: modbus_client
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspace
    # restart: always
    command: tail -f /dev/null
    networks:
      - lan-bridge
  modbusclient2:
    container_name: modbus_client2
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspace
    # restart: always
    command: tail -f /dev/null
    networks:
      - lan-bridge
  modbusclient3:
    container_name: modbus_client3
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspace
    # restart: always
    command: tail -f /dev/null
    networks:
      - lan-bridge
networks:
  lan-bridge:
    external: true